---
# Numpy
---

How to use this notebook:

- First, work through the prerequisites in [1. Prerequisites](#1-prerequisites).
- Then, work though [2. Nympy Basics](#2-numpy-basics) to [7. Fancy Indexing](#7-fancy-indexing).

This notebook covers:

- [1. Prerequisites](#1-prerequisites) 
- [2. Nympy Basics](#2-numpy-basics)
  - [2.1 Creating Numpy Arrays from Python Lists](#21-creating-numpy-arrays-from-python-lists)
  - [2.2 Creating Numpy Arrays from Scratch](#22-creating-numpy-arrays-from-scratch)
  - [2.3 Numpy Standard Data Types](#23-numpy-standard-data-types)
- [3. The Basics of Numpy Arrays](#3-the-basics-of-numpy-arrays)
  - [3.1 Numpy Array Attributes](#31-numpy-array-attributes)
  - [3.2 Array Indexing](#32-array-indexing)
  - [3.3 Array Slicing](#33-array-slicing)
  - [3.4 Array Slicing and Copies](#34-array-slicing-and-copies)
  - [3.5 Reshaping of Arrays](#35-reshaping-of-arrays)
  - [3.6 Array Concatenation](#36-array-concatenation)
  - [3.7 Array Splitting](#37-array-splitting)
- [4. Computation on Numpy Arrays (ufuncs)](#4-computation-on-numpy-arrays-ufuncs)
  - [4.1 Array Arithmetic](#41-array-arithmetic)
  - [4.2 Absolute Value](#42-absolute-value)
  - [4.3 Trigonometric Functions](#43-trigonometric-functions)
  - [4.4 Exponents and Logarithms](#44-exponents-and-logarithms)
  - [4.5 Aggregates](#45-aggregates)
  - [4.6 Aggregations](#46-aggregations)
- [5. Computations on Arrays: Broadcasting](#5-computations-on-arrays-broadcasting)
  - [5.1 Rules of Broadcasting](#51-rules-of-broadcasting)
  - [5.2 Broadcasting Example 1](#52-broadcasting-example-1)
  - [5.3 Broadcasting Example 2](#53-broadcasting-example-2)
  - [5.4 Broadcasting Example 3](#54-broadcasting-example-3)
- [6. Comparisons, Masks, and Boolean Logic](#6-comparisons-masks-and-boolean-logic)
- [7. Fancy Indexing](#7-fancy-indexing)

---
# 1. Prerequisites
---

Let's make sure you have a working Python virtual environment.

- If you don't already have a working environment, run the code below in a terminal (Windows/Linux: `Ctrl + J`, MacOS: `Cmd + J`).

  ```bash
  conda create -y -p ./.conda python=3.12
  conda activate ./.conda
  python -m pip install --upgrade pip
  pip install ipykernel jupyter pylance numpy pandas matplotlib seaborn bokeh plotly
  pip install dash dash-bootstrap-components openpyxl lxml pycountry
  ```

- Then, make sure you have chosen that environment by clicking `Select Kernel` in the top right of this Notebook.

Alternatively, you can run this Notebook in Google CoLab.
- Click [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/paga-hb/C1VI1B_2025/blob/main/workshop2/numpy.ipynb)

- In Google CoLab, choose `File -> Save a Copy in Drive`.
- Now you can work through the Notebook cells in Google CoLab.

---
# 2. Numpy Basics
---

- We will run all Python code examples within this Notebook, but remember you can always place the code in a `.py` file, e.g. `main.py`, open a terminal (Windows/Linux: `Ctrl + J`, MacOS: `Cmd + J`) and execute the command `python main.py`, making sure you are running the command within the Python virtual environment (`conda activate ./.conda`).

- To use numpy, we must:
  - `pip install numpy`
  - `import numpy as np`

---
## 2.1 Creating Numpy Arrays from Python Lists

- We can use `np.array()` to create a numpy array from a Python list.
- Unlike Python lists, a numpy array can only contain elements of the same type.
- To explicitly set the array’s type, we can use the `dtype` keyword.
- Numpy arrays can also be multidimensional (e.g. 3 rows, 2 columns).

In [10]:
import numpy as np

a = np.array([1, 4, 2, 5, 3])
print(a)
print(a.dtype)
print(type(a))

print()

a = np.array([3.14, 4, 2, 3])
print(a)
print(a.dtype)

print()

a = np.array([1, 2, 3, 4], dtype='float32')
print(a)
print(a.dtype)

print()

a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
print(a.dtype)

[1 4 2 5 3]
int64
<class 'numpy.ndarray'>

[3.14 4.   2.   3.  ]
float64

[1. 2. 3. 4.]
float32

[[1 2]
 [3 4]
 [5 6]]
int64


---
## 2.2 Creating Numpy Arrays from Scratch

- `np.zeros()` is used to create an array of zeros (e.g. a 1x10 int array).
- `np.ones()`is used to create an array of ones (e.g. a 2x5 float array).
- `np.arange()` is similar to the Python `range()` function (start, stop, step).
- `np.linspace()` creates an array with linearly spaced values (start, stop, step).
- `np.random.random()` creates an array with uniformly distributed random values between `0` and `1`.
- `np.random.randint()` creates an array with random integers (e.g. between `0` and `9`).

In [14]:
a = np.zeros(10, dtype=int)
print(a)

print()

a = np.ones((2, 5), dtype=float)
print(a)

print()

a = np.arange(0, 20, 2)
print(a)

print()

a = np.linspace(0, 1, 5)
print(a)

print()

a = np.random.random((2, 3))
print(a)

print()

a = np.random.randint(0, 10, (2, 3))
print(a)

[0 0 0 0 0 0 0 0 0 0]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[ 0  2  4  6  8 10 12 14 16 18]

[0.   0.25 0.5  0.75 1.  ]

[[0.39405219 0.98475612 0.60325152]
 [0.71259358 0.19144495 0.94332491]]

[[1 5 7]
 [5 3 7]]


---
## 2.3 Numpy Standard Data Types

- Numpy arrays contain values of a single type.
- When constructing an array, you can specify the type using:
  - a string

    ```python
    np.zeros(10, dtype='int16')
    ```

  - the associated numpy object (enumeration)

    ```python
    np.zeros(10, dtype=np.int16)
    ```


<img src="../images/np-dtypes.png"></>

In [15]:
a = np.zeros(10, dtype='int16')
print(a)
print(a.dtype)

print()

a = np.zeros(10, dtype=np.int16)
print(a)
print(a.dtype)

[0 0 0 0 0 0 0 0 0 0]
int16

[0 0 0 0 0 0 0 0 0 0]
int16


---
# 3. The Basics of Numpy Arrays
---

Basic numpy array manipulations include:
- Attributes of arrays.
  - Determining the size, shape, memory consumption, and data types of arrays.
- Indexing of arrays.
  - Getting and setting the value of individual array elements.
- Slicing of arrays.
  - Getting and setting smaller subarrays within a larger array.
- Reshaping of arrays.
  - Changing the shape of a given array.
- Joining and splitting of arrays.
  - Combining multiple arrays into one, and splitting one array into many.

---
## 3.1 Numpy Array Attributes

- Each numpy array instance has some basic properties (attributes):
  - Number of dimensions (`ndim`)
  - Size of each dimension (`shape`)
  - Total number of elements (`size`)
  - Datatype (`dtype`)

In [20]:
a = np.random.randint(10, size=(3, 4, 5))
print(a)

print()

print("ndim: ", a.ndim)
print("shape:", a.shape)
print("size: ", a.size)
print("dtype:", a.dtype)

[[[1 8 4 0 4]
  [7 3 1 4 3]
  [3 5 4 8 5]
  [2 6 8 5 2]]

 [[0 1 7 8 7]
  [3 3 2 6 7]
  [2 5 6 0 2]
  [8 1 2 0 9]]

 [[9 3 3 9 0]
  [2 2 3 9 7]
  [0 7 5 1 1]
  [3 2 6 9 7]]]

ndim:  3
shape: (3, 4, 5)
size:  60
dtype: int64


---
## 3.2 Array Indexing

- Indexing works the same way as with Python lists.
  - Indexes are zero-based.
  - For a one-dimensional array, use the array variable’s name with an index within square brackets `[]` to read an element or to assign a value to an element.

    ```python
    value = x1[0]
    x1[0] = 12
    ```

  - For a multi-dimensional arrays, use the array variable’s name with a tuple of indexes (one for each dimension) within square brackets `[]`.

    ```python
    value = x2[0, 0]
    x2[0, 0] = 0
    ```

In [26]:
x1 = np.array([5,0,3,3,7,9])
print(f"x1 = {x1}")
print()
print(f"x1[0] = {x1[0]}")
print(f"x1[-1] = {x1[-1]}")
print()
x1[0] = 12
print(f"x1 = {x1}")

print()

x2 = np.array([[3, 5], [7, 6], [1, 9]])
print(f"x2 =\n{x2}")
print()
print(f"x2[0, 0] = {x2[0, 0]}")
print(f"x2[2, -1] = {x2[2, -1]}")
print()
x2[0, 0] = 0
print(f"x2 =\n{x2}")

x1 = [5 0 3 3 7 9]

x1[0] = 5
x1[-1] = 9

x1 = [12  0  3  3  7  9]

x2 =
[[3 5]
 [7 6]
 [1 9]]

x2[0, 0] = 3
x2[2, -1] = 9

x2 =
[[0 5]
 [7 6]
 [1 9]]


---
## 3.3 Array Slicing

- Slicing works the same way as with Python lists.
  - Slice notation uses the colon `:` character.
  - We access slices of an array `x` with `x [start:stop:step]`, with default values `start=0`, `stop=`<size of dimension>, `step=1`

    ```python
    x[1:7:2] # start=1, stop=7, step=2
    x[:5]
    # 1st 5 elements (start=0,stop=5,step=1)
    x[5:]
    # elements after index 5
    x[4:7]
    # middle sub-array (elements 5, 6 and 7)
    x[::2]
    # every other element (step=2)
    ```

  - If the `step` value is negative, the defaults for `start` and `stop` are swapped.

    ```python
    x[::-1] # reverse all elements
    ```

  - For multi-dimensional arrays, each dimension has its own set of `start:stop:step`

    ```python
    x[:1, :2] # 1st row (1st dim), 1st 2 cols (2nd dim)
    ```

In [30]:
x = np.arange(10)
print(f"x = {x}")
print()
print(f"x[1:7:2] = {x[1:7:2]}")
print(f"x[:5] = {x[:5]}")
print(f"x[5:] = {x[5:]}")
print(f"x[4:7] = {x[4:7]}")
print(f"x[::2] = {x[::2]}")
print(f"x[::-1] = {x[::-1]}")

print()

x2 = np.array([[3, 5], [7, 6], [1, 9]])
print(f"x2 =\n{x2}")
print()
print(f"x2[:1, :2] = {x2[:1, :2]}")

x = [0 1 2 3 4 5 6 7 8 9]

x[1:7:2] = [1 3 5]
x[:5] = [0 1 2 3 4]
x[5:] = [5 6 7 8 9]
x[4:7] = [4 5 6]
x[::2] = [0 2 4 6 8]
x[::-1] = [9 8 7 6 5 4 3 2 1 0]

x2 =
[[3 5]
 [7 6]
 [1 9]]

x2[:1, :2] = [[3 5]]


---
## 3.4 Array Slicing and Copies

- Note that Python list slices return copies, whereas Numpy array slices return views that refer to the same original array.

  ```python
  x2 = np.array([[3, 5], [7, 6], [1, 9]])
  x2_sub = x2[:2, :2]
  x2_sub[0, 0] = 0
  print(x2) # x2 modified where x2[0, 0] is 0
  ```

- To copy a sub-array returned from slicing a Numpy array, we can use the `copy()` method.

  ```python
  x2_sub_copy = x2[:2, :2].copy()
  x2_sub_copy[0, 1] = 0
  print(x2) # x2 unmodified, i.e. x2[0, 1] is 5
  ```

In [34]:
x2 = np.array([[3, 5], [7, 6], [1, 9]])
print(f"x2 =\n{x2}\n")

x2_sub = x2[:2, :2]
print(f"x2_sub =\n{x2_sub}\n")

x2_sub_copy = x2[:2, :2].copy()
print(f"x2_sub_copy =\n{x2_sub_copy}\n")

x2_sub[0, 0] = 0
x2_sub_copy[0, 1] = 0

print(f"x2 =\n{x2}")

x2 =
[[3 5]
 [7 6]
 [1 9]]

x2_sub =
[[3 5]
 [7 6]]

x2_sub_copy =
[[3 5]
 [7 6]]

x2 =
[[0 5]
 [7 6]
 [1 9]]


---
## 3.5 Reshaping of Arrays

- Arrays can be reshaped using the `reshape()` method.
  - The new shape is given as an argument.
  - The number of elements in the new shape must match   the number of elements in the original shape.
  - A view of the original array is returned (not a copy).

    ```python
    a = np.arange(1,10) # 1 dim, 9 elements
    m = a.reshape((3,3)) # 3x3 matrix
    ```

- Reshaping can also be done by adding additional dimensions using `np.newaxis` together with indexing and slicing.

  ```python
  x = np.array([1,2,3]) # 1 dim, 3 elements
  x.reshape((1,3))      # 1x3 row vector
  x[np.newaxis, :]      # 1x3 row vector
  x.reshape((3,1))      # 3x1 column vector
  x[:, np.newaxis]      # 3x1 column vector
  ```

In [40]:
a = np.arange(1, 10)
print(f"a = {a}\n")

m = a.reshape((3, 3))
print(f"m =\n{m}\n")

x = np.array([1, 2, 3])
print(f"x = {x}\n")

r1 = x.reshape((1,3))
print(f"r1 = {r1}\n")

r2 = x[np.newaxis, :]
print(f"r2 = {r2}\n")

c1 = x.reshape((3,1))
print(f"c1 =\n{c1}\n")

c2 = x[:, np.newaxis]
print(f"c2 =\n{c2}")

a = [1 2 3 4 5 6 7 8 9]

m =
[[1 2 3]
 [4 5 6]
 [7 8 9]]

x = [1 2 3]

r1 = [[1 2 3]]

r2 = [[1 2 3]]

c1 =
[[1]
 [2]
 [3]]

c2 =
[[1]
 [2]
 [3]]


---
## 3.6 Array Concatenation

- Two or more arrays can be joined together using the function `np.concatenate()`

In [43]:
x = np.array([10, 20, 30])
y = np.array([40, 50, 60])
z = np.array([[1, 2, 3], [4, 5, 6]])

print(f"x = {x}")
print(f"y = {y}")
print(f"z =\n{z}\n")

a = np.concatenate([x, y])
print(f"a = {a}\n")

a = np.concatenate([z, z], axis=0)
print(f"a =\n{a}\n")

a = np.concatenate([z, z], axis=1)
print(f"a =\n{a}")

x = [10 20 30]
y = [40 50 60]
z =
[[1 2 3]
 [4 5 6]]

a = [10 20 30 40 50 60]

a =
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]

a =
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


- We can also join arrays using the functions `np.vstack()` and `np.hstack()`

In [46]:
x = np.array([1, 2, 3])
y = np.array([[4, 5, 6], [7, 8, 9]])
z = np.array([[10], [11]])

print(f"x = {x}")
print(f"y =\n{y}")
print(f"z =\n{z}\n")

a = np.vstack([x, y])
print(f"a =\n{a}\n")

a = np.hstack([y, z])
print(f"a =\n{a}")

x = [1 2 3]
y =
[[4 5 6]
 [7 8 9]]
z =
[[10]
 [11]]

a =
[[1 2 3]
 [4 5 6]
 [7 8 9]]

a =
[[ 4  5  6 10]
 [ 7  8  9 11]]


---
## 3.7 Array Splitting

- An array can be split using the function `np.split()`, where a list of indices is given for the split points.

In [47]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(x)

x1, x2, x3 = np.split(x, [3, 6])
print(x1, x2, x3)

[1 2 3 4 5 6 7 8 9]
[1 2 3] [4 5 6] [7 8 9]


- We can also use the functions `np.hsplit()` and `np.vsplit()`

In [51]:
y = np.arange(16).reshape((4,4))
print(y)

print()

upper, lower = np.vsplit(y, [2])
print(upper)
print()
print(lower)

print()

left, right = np.hsplit(y, [2])
print(left)
print()
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[0 1 2 3]
 [4 5 6 7]]

[[ 8  9 10 11]
 [12 13 14 15]]

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


---
# 4. Computation on Numpy Arrays (ufuncs)
---

- The key to fast computations on Numpy arrays is via vectorized operations.
- They are generally implemented via Numpy’s **universal functions (ufuncs)**.


---
## 4.1 Array Arithmetic

- The arithmetic ufuncs overload Python’s operators to perform vectorized operations on Numpy arrays instead of using loops.

  ```python
  x = np.arange(4) # [0 1 2 3]
  x = x + 2
  # [2 3 4 5]
  ```

- The equivalent ufuncs can be called directly via the syntax `np.<ufunc>`

  ```python
  x = np.arange(4) # [0 1 2 3]
  x = np.add(x, 2) # [2 3 4 5]
  ```

<img src="../images/np-arithmetic-ufuncs.png">

- The overloaded arithmetic operators `+`, `-`, `*`, `/`, `//`, `**`, and `%` work with Numpy arrays.
- We can also compute expressions containing Numpy arrays with the overloaded arithmetic operators.


In [52]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)
print("-x =", -x)
print("x ** 2 =", x ** 2)
print("x % 2 =", x % 2)
print("-(0.5*x + 1) ** 2 =", -(0.5*x + 1) ** 2)
print("np.add(x, 2) =", np.add(x, 2))

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2 = [0 1 0 1]
-(0.5*x + 1) ** 2 = [-1.   -2.25 -4.   -6.25]
np.add(x, 2) = [2 3 4 5]


---
## 4.2 Absolute Value

- Numpys’ ufunc for the absolute value is `np.absolute()` or `np.abs()`.
- Numpy also understands Python’s built-in function `abs()`.

In [53]:
x = np.array([-2, -1, 0, 1, 2])
print(x)

print(np.absolute(x))
print(np.abs(x))
print(abs(x))

[-2 -1  0  1  2]
[2 1 0 1 2]
[2 1 0 1 2]
[2 1 0 1 2]


---
## 4.3 Trigonometric Functions

- Numpy provides ufuncs for the trigonometric functions.

In [55]:
theta = np.linspace(0, np.pi, 3)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


- Numpy also provides ufuncs for the inverse trigonometric functions.

In [56]:
x = [-1, 0, -1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, -1]
[-1.57079633  0.         -1.57079633]
[3.14159265 1.57079633 3.14159265]
[-0.78539816  0.         -0.78539816]


---
## 4.4 Exponents and Logarithms

- Numpy provides ufuncs for the exponential functions.

In [57]:
x = [1, 2, 3]
print(x)
print(np.exp(x))
print(np.exp2(x))
print(np.power(3, x))

[1, 2, 3]
[ 2.71828183  7.3890561  20.08553692]
[2. 4. 8.]
[ 3  9 27]


- Numpy also provides ufuncs for logarithmic functions.

In [58]:
x = [1, 2, 4, 10]
print(x)
print(np.log(x))
print(np.log2(x))
print(np.log10(x))

[1, 2, 4, 10]
[0.         0.69314718 1.38629436 2.30258509]
[0.         1.         2.         3.32192809]
[0.         0.30103    0.60205999 1.        ]


---
## 4.5 Aggregates

- If we want to reduce an array with a particular operation, we can use the `reduce()` method of any ufunc.
- A reduce repeatedly applies a given operation to the elements of an array until only a single result remains.
- The `accumulate()` method repeatedly applies a given operation, but stores the intermediate results.

In [60]:
x = np.arange(1, 6)
print(x)

print()

print(np.add.reduce(x))
print(np.multiply.reduce(x))

print()

print(np.add.accumulate(x))
print(np.multiply.accumulate(x))

[1 2 3 4 5]

15
120

[ 1  3  6 10 15]
[  1   2   6  24 120]


---
## 4.6 Aggregations

- Numpy’s aggregation functions allow you to summarize the typical numerical values (statistics) in a dataset.

<img src="../images/np-aggregations.png">

In [62]:
x = np.arange(1, 6)
print(x)

print( np.min(x) )
print( np.max(x) )

print( x.min() )
print( x.max() )

[1 2 3 4 5]
1
5
1
5


- Aggregations can be applied to one-dimensional arrays.

In [65]:
x = np.arange(1, 6)
print(x)

print()

print(x.min())
print(x.max())
print(x.mean())
print(x.std())

print()

print(np.percentile(x, 25))
print(np.median(x))
print(np.percentile(x, 75))

[1 2 3 4 5]

1
5
3.0
1.4142135623730951

2.0
3.0
4.0


- Aggregations can be applied to multi-dimensional arrays.

In [67]:
x = np.array([[1, 2 ,3],[4, 5, 6]])
print(x)

print()

print(x.sum())
print(x.min(axis=0))
print(x.max(axis=1))

[[1 2 3]
 [4 5 6]]

21
[1 2 3]
[3 6]


---
# 5. Computations on Arrays: Broadcasting
---

- Applying functions to two arrays usually requires the arrays to be of the same shape.

    ```python
    a = np.array([0, 1, 2])
    b = np.array([5, 5, 5])
    print(a + b) # [5 6 7]
    ```

- Numpy **broadcasting** allows us to apply functions to **arrays of different shapes**.

    ```python
    print(a + 5) # [5 6 7]
    ```

- Broadcasting creates **temporary arrays** in memory during the computation to enable the operation.

    ```python
    a + 5 → [0 1 2] + 5 → [0 1 2] + [5 5 5] → [5 6 7]
    # scalar 5 is “broadcast” into a temporary 3-element array
    ```

---
## 5.1 Rules of Broadcasting

Numpy broadcasting follows a strict set of rules to determine the interaction between two arrays.

```python
M = np.ones((2,3)) # M.shape = (2, 3)
a = np.arange(3)   # a.shape = (3,)
M + a              # Needs broadcasting
```

- **Rule 1**: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

  ```python
  M.shape # (2, 3)
  a.shape # (3,) → pad a’s shape with 1 on the left → (1, 3)
  ```

- **Rule 2**: If the shape of the two arrays does not match in a dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

  ```python
  (2, 3)
  (1, 3) # → stretch a’s dimension with shape 1 to match M’s dimension → (2, 3)
  ```

- **Rule 3**: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

---
## 5.2 Broadcasting Example 1

In [75]:
M = np.ones((2,3))
print(f"M =\n{M}")
print(f"M.shape = {M.shape}")

print()

a = np.arange(3)
print(f"a = {a}")
print(f"a.shape = {a.shape}")

print("""
# Rule 1: Pad a’s shape with a 1 from the left
# M: (2, 3)
# a: (3,) → (1, 3) """)

print("""
# Rule 2: Stretch dimension with a 1 to match other
# M: (2, 3)
# a: (1, 3) → (2, 3)
""")

res = M + a
print(f"res =\n{res}")
print(f"res.shape = {res.shape}")

M =
[[1. 1. 1.]
 [1. 1. 1.]]
M.shape = (2, 3)

a = [0 1 2]
a.shape = (3,)

# Rule 1: Pad a’s shape with a 1 from the left
# M: (2, 3)
# a: (3,) → (1, 3) 

# Rule 2: Stretch dimension with a 1 to match other
# M: (2, 3)
# a: (1, 3) → (2, 3)

res =
[[1. 2. 3.]
 [1. 2. 3.]]
res.shape = (2, 3)


---
## 5.3 Broadcasting Example 2

In [76]:
a = np.arange(3).reshape((3, 1))
print(f"M =\n{a}")
print(f"M.shape = {a.shape}")

print()

b = np.arange(3)
print(f"a = {b}")
print(f"a.shape = {b.shape}")

print("""
# Rule 1: Pad b’s shape with a 1 from the left
# a: (3, 1)
# b: (3,) → (1, 3) """)

print("""
# Rule 2: Stretch dimension with a 1 to match other
# a: (3, 1) → (3, 3)
# b: (1, 3) → (3, 3)
""")

res = a + b
print(f"res =\n{res}")
print(f"res.shape = {res.shape}")

M =
[[0]
 [1]
 [2]]
M.shape = (3, 1)

a = [0 1 2]
a.shape = (3,)

# Rule 1: Pad b’s shape with a 1 from the left
# a: (3, 1)
# b: (3,) → (1, 3) 

# Rule 2: Stretch dimension with a 1 to match other
# a: (3, 1) → (3, 3)
# b: (1, 3) → (3, 3)

res =
[[0 1 2]
 [1 2 3]
 [2 3 4]]
res.shape = (3, 3)


---
## 5.4 Broadcasting Example 3

In [78]:
M = np.ones((3,2))
print(f"M =\n{M}")
print(f"M.shape = {M.shape}")

print()

a = np.arange(3)
print(f"a = {a}")
print(f"a.shape = {a.shape}")

print("""
# Rule 1: Pad a’s shape with a 1 from the left
# M: (3, 2)
# a: (3,) → (1, 3) """)

print("""
# Rule 2: Stretch dimension with a 1 to match other
# M: (3, 2)
# a: (1, 3) → (3, 3) """)

print("""
# Rule 3: shapes disagree in dimension 2, and neither is 1
# M: (3, 2)
# a: (3, 3)
""")

try:
    res = M + a
except Exception as e:
    print(type(e).__name__, e)

M =
[[1. 1.]
 [1. 1.]
 [1. 1.]]
M.shape = (3, 2)

a = [0 1 2]
a.shape = (3,)

# Rule 1: Pad a’s shape with a 1 from the left
# M: (3, 2)
# a: (3,) → (1, 3) 

# Rule 2: Stretch dimension with a 1 to match other
# M: (3, 2)
# a: (1, 3) → (3, 3) 

# Rule 3: shapes disagree in dimension 2, and neither is 1
# M: (3, 2)
# a: (3, 3)

ValueError operands could not be broadcast together with shapes (3,2) (3,) 


---
# 6. Comparisons, Masks, and Boolean Logic
---

- Numpy has overloaded the comparison and bitwise boolean operators and has equivalent ufuncs.

<img src="../images/np-relational-operators.png"></img>

<img src="../images/np-bitwise-operators.png"></img>

- Applying comparisons and boolean logic on Numpy arrays result in an array where each element is a `bool` (`True`, `False`).

In [82]:
x = np.array([1, 2, 3, 4, 5])
print(x)

print()

print(x < 3)
print((x < 4) & (x > 1))

print()

print( np.sum(x < 3) )

[1 2 3 4 5]

[ True  True False False False]
[False  True  True False False]

2


- The boolean arrays can be used as masks to index into an array an select elements where the mask is `True`.

In [86]:
x = np.array([1, 2, 3, 4, 5])
print(x)

print( x[x < 3] )

[1 2 3 4 5]
[1 2]


---
# 7. Fancy Indexing
---

- Fancy indexing means passing an array of indices to access multiple array elements at once.

In [89]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(x)

print()

ind = [3, 7, 4]
print(x[ind])

[1 2 3 4 5 6 7 8 9]

[4 8 5]


- With fancy indexing, the shape of the result reflects the shape of the index array (not the shape of the array being indexed).

In [90]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(x)

print()

ind = np.array([[3, 7], [4, 5]])
print(x[ind])

[1 2 3 4 5 6 7 8 9]

[[4 8]
 [5 6]]
